baseURL = "https://polRk.com"
languageCode = "en"
title = "The polRk"
theme = "polrk"

[params]
  Name = "The polRk"
  Author = "Vladislav Polyakov"
  Description = "Technical Director and Senior Software Enginner."
  Copyright = "Copyright (c) 2020 Vladislav Polyakov. All Rights Reserved."
  Keywords = "polRk,website,programmer,freelancer"
  GoogleAnalytics = "G-PSPDX1GNH8"
